experiment:
    id: bikes_s_4_padded_2_eval

##Data
data:
    data_dir: '/home/ekirby/scania/ekirby/datasets/bikes_from_nuscenes/bikes_from_nuscenes_train_val.json'
    resolution: 0.05
    dataloader: 'nuscenes'
    coordinates: 'cylindrical'
    points_per_object: 100
    align_objects: True
    stacking_type: pad

##Training
train:
    uncond_prob: 0.1
    uncond_w: 6.
    n_gpus: 1
    num_workers: 4
    max_epoch: 10000
    lr: 0.0001
    batch_size: 16
    decay_lr: 1.0e-4
    class_conditional: False
    ema: True

diff:
    beta_start: 3.5e-5
    beta_end: 0.007
    beta_func: 'linear'
    t_steps: 1000
    s_steps: 50
    reg_weight: 0.0
    visualize: False
    num_val_samples: 10

##Network
model:
    out_dim: 96
    embeddings: 'cyclical'
    num_conditions: 7
    cyclic_conditions: 1
    relative_angles: True
    config: DiT-S/4
    attention: normal
    pretrained: False
