experiment:
    id: shapenet_s_4_1

##Data
data:
    data_dir: '/home/ekirby/scania/ekirby/datasets/motorcycles_from_shapenet/03790512'
    resolution: 0.05
    dataloader: 'shapenet'
    coordinates: 'cylindrical'
    points_per_object: 2048
    align_objects: False

##Training
train:
    uncond_prob: 0.1
    uncond_w: 6.
    n_gpus: 1
    num_workers: 4
    max_epoch: 10000
    lr: 0.0001
    batch_size: 16
    decay_lr: 1.0e-4
    class_conditional: False
    ema: False

diff:
    beta_start: 3.5e-5
    beta_end: 0.007
    beta_func: 'linear'
    t_steps: 1000
    s_steps: 50
    reg_weight: 0.0
    visualize: False
    num_val_samples: 10

##Network
model:
    out_dim: 96
    embeddings: 'cyclical'
    num_conditions: 8
    cyclic_conditions: 2
    relative_angles: False
    config: DiT-S/4
    attention: window
