experiment:
    id: multiclass_xs_4_cross_voxel_max_2a_1
##Data
data:
    data_dir: /home/ekirby/scania/ekirby/datasets/all_objects_nuscenes_cleaned/all_objects_nuscenes_cleaned_train_val.json
    resolution: 0.05
    dataloader: 'nuscenes'
    points_per_object: -1
    align_objects: False
    stacking_type: max

##Training
train:
    uncond_prob: 0.1
    uncond_w: 6.
    n_gpus: 5
    num_workers: 32
    max_epoch: 10000
    lr: 0.0001
    batch_size: 16
    decay_lr: 1.0e-4
    class_conditional: True
    ema: True

diff:
    beta_start: 3.5e-5
    beta_end: 0.007
    beta_func: 'linear'
    t_steps: 1000
    s_steps: 50
    reg_weight: 0.0
    visualize: False
    num_val_samples: 10

##Network
model:
    embeddings: voxel
    num_conditions: 8
    cyclic_conditions: 2
    relative_angles: False
    config: DiT-S/4
    attention: cross
    pretrained: False
