experiment:
    id: xs_4_2a_cross_point
##Data
data:
    data_dir: '/home/ekirby/scania/ekirby/datasets/bikes_from_nuscenes/bikes_from_nuscenes_train_val.json'
    dataloader: 'nuscenes'
    points_per_object: -1
    align_objects: False
    stacking_type: max

##Training
train:
    uncond_prob: 0.1
    uncond_w: 6.
    n_gpus: 1
    num_workers: 8
    max_epoch: 2000
    lr: 0.0001
    batch_size: 16
    decay_lr: 1.0e-4
    class_conditional: False
    ema: True

diff:
    beta_start: 3.5e-5
    beta_end: 0.007
    beta_func: 'linear'
    t_steps: 1000
    s_steps: 50
    reg_weight: 0.0
    visualize: False
    num_val_samples: 10

##Network
model:
    embeddings: point
    num_conditions: 8
    cyclic_conditions: 2
    relative_angles: False
    config: DiT-XS/4
    attention: cross
    pretrained: False
