experiment:
    id: xs_4_1a_self_point_pretrained_eval
##Data
data:
    data_dir: '/home/ekirby/scania/ekirby/datasets/bikes_from_nuscenes/bikes_from_nuscenes_train_val.json'
    dataloader: 'nuscenes'
    points_per_object: -1
    align_objects: True
    stacking_type: max
    normalize_points: False

##Training
train:
    uncond_prob: 0.1
    uncond_w: 1.
    n_gpus: 4
    num_workers: 32
    max_epoch: 2000
    lr: 0.0001
    batch_size: 16
    decay_lr: 1.0e-4
    class_conditional: False
    ema: True

diff:
    beta_start: 3.5e-5
    beta_end: 0.007
    beta_func: 'linear'
    t_steps: 1000
    s_steps: 50
    reg_weight: 0.0
    visualize: False
    num_val_samples: 10

##Network
model:
    embeddings: point
    num_conditions: 7
    cyclic_conditions: 1
    relative_angles: True
    config: DiT-XS/4
    attention: flash
    pretrained: True
    in_channels: 3
